title: PyTricks
author: Jimit Dholakia
logo: py_logo.png
exclude_patterns: ['README.md','.github/CONTRIBUTING.md']

launch_buttons:
  binderhub_url: https://mybinder.org
  colab_url: https://colab.research.google.com
  thebe: true

repository:
  url: https://github.com/jimit105/pytricks
    
html:
  google_analytics_id: UA-136790987-1
  home_page_in_navbar: true
  baseurl: https://jimit105.github.io/pytricks
  use_edit_page_button: true
  use_repository_button : true
  use_issues_button: true
  favicon: favicon_py.png
    
sphinx:
  extra_extensions: ['sphinx_sitemap', 'yasfb']
  config:
    html_extra_path: ['robots.txt']
    feed_base_url: 'https://jimit105.github.io/pytricks'
    feed_author: 'Jimit Dholakia'
